### ISSUE TITLE
I would like to create a Code of Conduct markdown file.

### ISSUE THREAD

**Issue by sumitbishti** [lyqht/Octokit-lite#13]

**Comment by lyqht** [comment]
Sure thing!

**Comment by sumitbishti** [comment]
Sure, I will mention all the appropriate references. But, could you please add Hacktoberfest label onto this issue.

**Comment by lyqht** [comment]
hi @sumitbishti, i have added the label.

**Comment by sumitbishti** [comment]
> hi @sumitbishti, i have added the label.

Thank you!
