### ISSUE TITLE
Show mock data if user is not logged in

### ISSUE THREAD

**Issue by lyqht** [lyqht/Octokit-lite#14]
## Description

At the moment, if you are not logged into the app, when you click on either Unfork or TopicSpace, you do not get redirected to them and you would still see a loading indicator. While the quick fix is to add disabled state if the user is not present, I would prefer it if users can see what the app offers without logging in yet.

## Suggested solution

1. Create mock data e.g. a fake user john@smith.com, with some repositories, deleted records and updated records. 
2. Set these mock data as **server side props** if no user can be found.
3. Action buttons (with the text 'Next ->') on both TopicSpace and Unfork should be disabled and not trigger any API call if no user is logged in.

**Comment by Lofty-Brambles** [comment]
With respect to #2 - Would it be good to instead add assets showing how the page works over adding mock data?

**Comment by lyqht** [comment]
Good point. Adding assets might suffice over adding mock data. Thinking about the pros and cons of having mock data:

Pros:
- Mock data can be useful for testing if we add unit tests in the future
- User can get a more direct experience without logging in

Cons:
- The "nice" experience is hidden behind a click of the app icon rather than being felt directly at the landing page (#2), so this will reduce user retention/engagement.

It does feels that the single con outweighs the pros, so for now, I agree that #2 should be worked on instead. I will close this issue for now, but it can be worked on in the future when we introduce frontend tests for this project.
