### ISSUE TITLE
[Unfork] Error when deleting too many repositories

### ISSUE THREAD

**Issue by lyqht** [lyqht/Octokit-lite#3]
## Description

When attempting to delete many repositories e.g. >20, this could be observed in the console.

```
Uncaught (in promise) SyntaxError: Unexpected token 'A', "An error o"... is not valid JSON
```

It seems to be caused by GitHub's API

## Solution

- To log out the error in full
- Error handling & retry request

**Comment by jacobtyq** [comment]
Will be taking a look at this
