### ISSUE TITLE
[Unlabel] Remove labels from all issues in selected repos

### ISSUE THREAD

**Issue by lyqht** [lyqht/Octokit-lite#33]
## Description

This will be a new microapp similar to TopicSpace. The use case is for maintainers to remove `hacktoberfest` label easily from all their participating projects after the event as well as any other labels that they don't want to see in their projects anymore.

## Tasks

- The index page UI will be similar, but instead of topics, users can input labels.
- On action confirm, it will call a different API route which calls [the GitHub API to remove the given labels](https://docs.github.com/en/rest/issues/labels#remove-a-label-from-an-issue) from all issues in selected repos.
- The backend will also add a new UpdatedRecord in the Supabase table with `initialRepoDetails` containing the issues with their previous labels and `updatedFields` with the new list of labels.
- The history page will show removed labels for each repo.
- Add button to home page to go to Unlabel
- Add icon for Unlabel
- Add to README what Unlabel does a demo GIF

## Notes

Related PRs should be merged to `feature/unlabel` first before merging to main.

**Comment by Dolir** [comment]
Hi, can i get assigned ?

**Comment by lyqht** [comment]
Hi @Dolir, as this issue is quite a big, do you understand the scope and the tasks to go about implementing it?

**Comment by Dolir** [comment]
Yeah, i'm sure i can handle this.

**Comment by lyqht** [comment]
Okie cool let me know if u encounter any issues!
