### ISSUE TITLE
[Unfork] Add FAQ popup

### ISSUE THREAD

**Issue by lyqht** [lyqht/Octokit-lite#35]
## Description 

To add a FAQ button in the form of a question icon to the Unfork index page. It can be located at the top right corner of the page.

On click of this button, it should bring up a popup that shows the FAQ:
- What does Unfork do?
  - Delete forks and repos easily with a few clicks.
- Why use Unfork?
  - It is estimated that Unfork can help you to save your search and operation time by ~5mins for every 1 repo you want to delete.
  - With Unfork, you get to see all your repos instantly. You can see your repos sorted by whether they are forked or created by you, or sort them by the last push date to determine at a glance whether to keep the repo or not.
  - If you try to delete 1 repo manually on GitHub, you need to go to the repo page directly, go through 2FA, type the repo's name and then click confirm button.
  - If you have many repos that you want to delete, the manual process above will be very tedious, especially with GitHub's paginated UI.
- How do I restore my deleted projects?
  - Please refer to the GitHub documentation on restoring your deleted projects. You may only restore projects that are deleted in the last 90 days.
- How do I detach my forks instead of deleting them?
  - At the moment, there's no easy way of detaching a fork. You have to contact GitHub's support ([Reference](https://stackoverflow.com/questions/29326767/unfork-a-github-fork-without-deleting/41486339#41486339))

You can either hardcode the html tags for each question to be h2, or you can try to render the above as a markdown (preferred)

## Context 

It seems that in [this StackOverflow thread](https://stackoverflow.com/questions/29326767/unfork-a-github-fork-without-deleting/41486339#41486339), users have a different understanding of what it means to Unfork (it's not an official term). 

For me, I thought it simply means to **delete the forked repo**, but it turns out that there's another concept and use case of **detaching** a fork. [Example project developed from a fork](https://github.com/nimeshnayaju/tlslides) - which I think should be detached.
 
However, there isn't an easy way to support this detach behavior on Octokit-lite, hence I'm suggesting to just add a FAQ where users who came to Unfork with the intent to detach their forked repos can understand and adjust theirnexpectations for using Unfork.

**Comment by its-me-Harsh-Anand** [comment]
Hey @lyqht, I want to work on this issue. Can you please assign me?

Also, in the popup everything is to be included that is written only in description of the issue?

**Comment by lyqht** [comment]
Yeap, including the hyperlinks. if you can think up more to add/ rephrase feel free to do so.

Assigned it to you @its-me-Harsh-Anand
