### ISSUE TITLE
Better UI for deleted items

### ISSUE THREAD

**Issue by lyqht** [lyqht/Octokit-lite#5]
## Current UI

Very plain and dull, and also coz I don't think users care why they deleted them as of implementation now.

<img width="663" alt="image" src="https://user-images.githubusercontent.com/35736525/191918078-613f20a5-61cd-4cef-b14d-06f7037a9c4b.png">

## Relevant Code

The relevant component code can be found at `unfork/history.tsx`, under `renderDescription()` prop.

## Solution

Was thinking for it to be more like a [table component](https://daisyui.com/components/table/).

Feel free to propose a better UI here. Once approved then you can proceed with a PR

**Comment by Lofty-Brambles** [comment]
![Untitled-2022-09-30-1725 excalidraw](https://user-images.githubusercontent.com/100270817/193266247-de8cdbcd-ba99-4b19-9a16-ed13a4179c38.svg)
This is what I had envisioned right now, and I think it would be good with a table component.

**Comment by lyqht** [comment]
yeap a table component with a filters+sort option next to the back button will be cool 😄 thanks for the mockup.
