### ISSUE TITLE
Allow users to sort repos by inactivity level

### ISSUE THREAD

**Issue by lyqht** [lyqht/Octokit-lite#8]
## Description

I have added a field called `lastPushDate` for users to identify the date of last activity on the repository, however, i haven't made the dropdown sortable by this field.

## Suggested Solution

- Hence, this issue requires an addition of a typical sort symbol for users to click on at the group label to sort by the lastPushDate.
- Dev working on this issue needs to make sure that sorting within one group does not affect sorting in the other group (e.g. sort by descending date in the `forks` group should not affect repos shown in the `created by user` group`

**Comment by Ilikepizza2** [comment]
Hello @lyqht 
I'd like to work on this issue.
Can I be assigned?

**Comment by lyqht** [comment]
Sure thing, I have assigned you!
